# Setup
title:               Pardon the Interrupt
tagline:             'Matthew Sills'
description:         'Description here'
url:                 'https://mattsills.github.io'
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Matthew Sills
  url:               https://github.com/mattsills/
  email:             matthew.sills@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
